classifications = {
	"tag_1_applicability": [
		"Full Lifecycle",
		"Operations",
		"Post-Disbursement (CS)",
		"Pre-Disbursemnet (CP)"
	],
	"tag_2_area": [
		"Environmental",
		"Financial",
		"Informative",
		"Legal",
		"Security",
		"Technical"
	],
	"tag_3_covenant_type": [
		"Financial - Informative",
		"Financial - Negative",
		"Financial - Affirmative",
		"Non Financial - Affirmative",
		"Non Financial - Event of Default",
		"Non Financial - Informative",
		"Non Financial - Representation"
	],
	"tag_4_covenant_title_tag": [
		"Approvals",
		"Budget",
		"Certificate",
		"Confirmaion Documents",
		"Consequence EOD",
		"Consultant Appointment",
		"Credit Rating",
		"Default",
		"EoD",
		"Financial Statements",
		"Insurance",
		"Legal Documents",
		"Management Confirmation",
		"Prepayment",
		"Ratios",
		"Reports",
		"Representations & Warranties",
		"Sector",
		"Security Related",
		"Solvency",
		"Statutory Documents"
	],
	"tag_5_covenant_description_sub_tags": [
		"Additional Conditions",
		"Additional Security",
		"Annual Results - Audited",
		"Annual Results - Unaudited",
		"Applicable Laws",
		"Approvals, Filings"
		"Attachment",
		"Board Resolution",
		"Borrower Undertaking",
		"Breech Financial Documents",
		"Breech Project Documents",
		"Breach Project Documents, Creditor",
		"CA Cerificate",
		"Cease Operations",
		"Certificate by Authorized Officer",
		"Clear Title Confirmation",
		"Credit Rating",
		"Creditor",
		"Current Assets",
		"Debt / Equity",
		"Delayed Payment",
		"Director Declaration",
		"Dispose Assets",
		"DPN",
		"DSCR",
		"DSRA",
		"Email Indemnity, Fax Indemnity",
		"End Use Cerificate",
		"Enforce Security",
		"Excess Liabilities",
		"Execution",
		"Expert Report",
		"Expropriation",
		"Financial Budgets",
		"Income Tax - Guarantors",
		"Incorrect Utilization",
		"Insolvency",
		"Inspection",
		"Insurance Policy",
		"Leally Incorporated",
		"Lenders Engineer",
		"LIE Report",
		"Liquidation",
		"MAE",
		"Mandatory",
		"Misrepresentation",
		"MoA, AoA",
		"MOE",
		"Mortgage",
		"NDU",
		"Networth Certificate",
		"No Default",
		"No Litigation", 
		"No relation to director",
		"No relation to senior officer",
		"Operating TRA",
		"Other",
		"Other Document",
		"Other resolution mechanism",
		"Others",
		"Ownership",
		"Payment",
		"Personal Guarantee",
		"Pledge",
		"Pledge Agreement",
		"Proceedings",
		"Project Cost",
		"Repay Facility",
		"Revenue Agreement",
		"ROC Charge Filing",
		"ROC Filing",
		"SARFAESI",
		"Security Cover Ratio",
		"Security Creation",
		"Security Creation, Security Perfection",
		"Security Deficiency",
		"Shareholder Resolution",
		"Sue for creditors process",
		"Tax",
		"Termination, Suspension",
		"Third Party Security",
		"Title Deeds",
		"Title Search Report, Valuation Report",
		"True Information",
		"Unlawfulness",
		"Valid Approvals"
	],
	"Tag_6_User_Defined": [
		"(Blanks)",
		"PDC(1-n)",
		"PDC(1)"
	]
}
